### ISSUE TITLE
Using a UITableView

### ISSUE THREAD

**Issue by gholias** [justeat/ScrollingStackViewController#34]
Do you have an example showing how to stack a UITableViewController?
I found this post https://medium.com/@danielemargutti/efficient-scrolling-uistackview-in-swift-99f3d75fb12e that talks about a `StackContainble protocol` but I could not find anything in the files.

**Comment by gigisommo** [comment]
Sorry @gholias, as far as I know that protocol is not part of the ScrollingStackViewController component. I think that it was introduced in the forked version https://github.com/malcommac/ScrollingStackContainer used in the linked article. I would suggest you to do not try to use a table view within the scrolling stack view controller because it will means that there will be a scrollview (the table view of the table view controller) inside the ScrollingStackViewController's scrollview and they will both needs to scroll vertically. This is usually hard to manage.
